on:
  workflow_dispatch:

name: Make File Changes to GitHub Repo
jobs:
  make-file-changes:
    runs-on: ubuntu-latest
    steps:
    # Checkout code
    - uses: actions/checkout@v4

    # Add actions that modify files here
    - name: Modify files
      run: |
        echo "change files here"

    - name: Check for Changes
      id: check_changes
      run: |
        if [[ -n "$(git diff --exit-code)" ]]; then
          echo "Changes detected."
          echo "::set-output name=has_changes::true"
        else
          echo "No changes detected."
          echo "::set-output name=has_changes::false"
        fi

    - name: Commit and Push Changes
      if: steps.check_changes.outputs.has_changes == 'true'
      run: |
        # configure user
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

        # stage any file changes to be committed
        git add .

        # make commit with staged changes
        git commit -m 'files changed'

        # push the commit back up to source GitHub repository
        git push
